// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCpM4mgaj7DARdxtNxSnWzAHjzPWj4EwRQ',
    appId: '1:286696696685:web:6e26ad1ae72416cc2ac864',
    messagingSenderId: '286696696685',
    projectId: 'remote-config-demo-ed7a1',
    authDomain: 'remote-config-demo-ed7a1.firebaseapp.com',
    storageBucket: 'remote-config-demo-ed7a1.appspot.com',
    measurementId: 'G-SHN31CNRF6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC_UjhlxIqQRY0XQZJw0QGtw0V02Ui_cYw',
    appId: '1:286696696685:android:df013d981c1120bd2ac864',
    messagingSenderId: '286696696685',
    projectId: 'remote-config-demo-ed7a1',
    storageBucket: 'remote-config-demo-ed7a1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCP5iOlwK0aJmP2YTs58uo8_ilnfJ94Bg4',
    appId: '1:286696696685:ios:7f141991636b23e62ac864',
    messagingSenderId: '286696696685',
    projectId: 'remote-config-demo-ed7a1',
    storageBucket: 'remote-config-demo-ed7a1.appspot.com',
    iosClientId: '286696696685-k08gh2i060j9ra7lmltpgd5fuck4i5on.apps.googleusercontent.com',
    iosBundleId: 'com.example.remoteConfigDemo',
  );
}
